# Generated by Django 4.2 on 2025-03-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Страна', 'verbose_name_plural': 'Страна'},
        ),
        migrations.AlterModelOptions(
            name='destination',
            options={'verbose_name': 'Путешествие', 'verbose_name_plural': 'Путешествия'},
        ),
        migrations.AlterModelOptions(
            name='travelpackage',
            options={'verbose_name': 'Тур', 'verbose_name_plural': 'Туры'},
        ),
        migrations.AddField(
            model_name='country',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
