# Generated by Django 4.2 on 2025-03-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0002_alter_country_options_alter_destination_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='extra_services',
            field=models.ManyToManyField(blank=True, to='travels.extraservice'),
        ),
    ]
