# Generated by Django 4.2 on 2025-03-23 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0003_extraservice_travelpackage_extra_services'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extraservice',
            options={'verbose_name': 'Дополнительные опции', 'verbose_name_plural': 'Дополнительные опции'},
        ),
    ]
